### ISSUE TITLE
[Help] Running repronum function

### ISSUE THREAD

**Issue by alexanderjanke** [Stochastik-TU-Ilmenau/COVID-19#3]
I've been trying to run your repronum-function found in the file `estimator.r` on the github-pages branch.

The function itself is defined as: 

```
repronum <- function(
    new.cases, # I
    profile, # w
    window = 1, # H
    delay = 0, # Delta
    conf.level = 0.95, # 1-alpha
    pad.zeros = FALSE,
    min.denominator = 5,
    min.numerator = 5
)
```

I'm kinda stuck on what profile #w is in this case. I tried calling the function with a multitude of values but every try results in the error:
`Error in stats::filter(new.cases, c(0, profile), method = "convolution",  : 
  'filter' is longer than time series`

For example I tried:
`repronum(500, 0)`

Any hints or help would be highly appreciated.

**Comment by matthias-g-** [comment]
`profile` is the "infectivity profile", see the [report](https://stochastik-tu-ilmenau.github.io/COVID-19/reports/repronum/repronum.pdf) for an explanation. The profile used for our estimations is `infectivity <- ...` defined at the beginning of `estimator.r`.
